// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.12.4
// source: genres.proto

package genprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gender struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Gender) Reset() {
	*x = Gender{}
	if protoimpl.UnsafeEnabled {
		mi := &file_genres_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gender) ProtoMessage() {}

func (x *Gender) ProtoReflect() protoreflect.Message {
	mi := &file_genres_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gender.ProtoReflect.Descriptor instead.
func (*Gender) Descriptor() ([]byte, []int) {
	return file_genres_proto_rawDescGZIP(), []int{0}
}

func (x *Gender) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Gender) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AllGenders struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Genders []*Gender `protobuf:"bytes,1,rep,name=genders,proto3" json:"genders,omitempty"`
}

func (x *AllGenders) Reset() {
	*x = AllGenders{}
	if protoimpl.UnsafeEnabled {
		mi := &file_genres_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllGenders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllGenders) ProtoMessage() {}

func (x *AllGenders) ProtoReflect() protoreflect.Message {
	mi := &file_genres_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllGenders.ProtoReflect.Descriptor instead.
func (*AllGenders) Descriptor() ([]byte, []int) {
	return file_genres_proto_rawDescGZIP(), []int{1}
}

func (x *AllGenders) GetGenders() []*Gender {
	if x != nil {
		return x.Genders
	}
	return nil
}

var File_genres_proto protoreflect.FileDescriptor

var file_genres_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x36, 0x0a, 0x0a, 0x41, 0x6c, 0x6c, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x12,
	0x28, 0x0a, 0x07, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x52, 0x07, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x32, 0x85, 0x02, 0x0a, 0x0d, 0x47, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x0c, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x1a, 0x0c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x0c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x1a, 0x0c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x0c, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x0c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x42, 0x79, 0x49, 0x64, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x12, 0x0e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x1a, 0x12, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x6c, 0x6c, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x22,
	0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_genres_proto_rawDescOnce sync.Once
	file_genres_proto_rawDescData = file_genres_proto_rawDesc
)

func file_genres_proto_rawDescGZIP() []byte {
	file_genres_proto_rawDescOnce.Do(func() {
		file_genres_proto_rawDescData = protoimpl.X.CompressGZIP(file_genres_proto_rawDescData)
	})
	return file_genres_proto_rawDescData
}

var file_genres_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_genres_proto_goTypes = []interface{}{
	(*Gender)(nil),     // 0: protos.Gender
	(*AllGenders)(nil), // 1: protos.AllGenders
	(*ById)(nil),       // 2: protos.ById
	(*Void)(nil),       // 3: protos.Void
}
var file_genres_proto_depIdxs = []int32{
	0, // 0: protos.AllGenders.genders:type_name -> protos.Gender
	0, // 1: protos.GenderService.CreateGender:input_type -> protos.Gender
	0, // 2: protos.GenderService.UpdateGender:input_type -> protos.Gender
	2, // 3: protos.GenderService.DeleteGender:input_type -> protos.ById
	2, // 4: protos.GenderService.GetByIdGender:input_type -> protos.ById
	0, // 5: protos.GenderService.GetAllGenders:input_type -> protos.Gender
	3, // 6: protos.GenderService.CreateGender:output_type -> protos.Void
	3, // 7: protos.GenderService.UpdateGender:output_type -> protos.Void
	3, // 8: protos.GenderService.DeleteGender:output_type -> protos.Void
	0, // 9: protos.GenderService.GetByIdGender:output_type -> protos.Gender
	1, // 10: protos.GenderService.GetAllGenders:output_type -> protos.AllGenders
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_genres_proto_init() }
func file_genres_proto_init() {
	if File_genres_proto != nil {
		return
	}
	file_users_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_genres_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gender); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_genres_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllGenders); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_genres_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_genres_proto_goTypes,
		DependencyIndexes: file_genres_proto_depIdxs,
		MessageInfos:      file_genres_proto_msgTypes,
	}.Build()
	File_genres_proto = out.File
	file_genres_proto_rawDesc = nil
	file_genres_proto_goTypes = nil
	file_genres_proto_depIdxs = nil
}
