basePath: /
definitions:
  genprotos.AllUsers:
    properties:
      users:
        items:
          $ref: '#/definitions/genprotos.UserRes'
        type: array
    type: object
  genprotos.UserReq:
    properties:
      email:
        type: string
      password:
        type: string
      user_name:
        type: string
    type: object
  genprotos.UserRes:
    properties:
      email:
        type: string
      id:
        type: string
      password:
        type: string
      user_name:
        type: string
    type: object
  handler.UserName:
    properties:
      userName:
        type: string
    type: object
  token.Tokens:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Library service
  version: "1.0"
paths:
  /user/{id}/borrowed_books:
    get:
      consumes:
      - application/json
      description: GetAll page
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: GetAll Successful
          schema:
            $ref: '#/definitions/genprotos.AllUsers'
        "401":
          description: Error while GetAll
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: GetAll User
      tags:
      - User
  /user/{id}/borrowing_history:
    get:
      consumes:
      - application/json
      description: GetAll page
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: GetAll Successful
          schema:
            $ref: '#/definitions/genprotos.AllUsers'
        "401":
          description: Error while GetAll
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: GetAll User
      tags:
      - User
  /user/delete/{id}:
    delete:
      consumes:
      - application/json
      description: Delete page
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Delete Successful
          schema:
            type: string
        "401":
          description: Error while Deleted
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Delete User
      tags:
      - User
  /user/get/{id}:
    get:
      consumes:
      - application/json
      description: GetById page
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: GetById Successful
          schema:
            $ref: '#/definitions/genprotos.UserRes'
        "401":
          description: Error while GetByIdd
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: GetById User
      tags:
      - User
  /user/getall:
    get:
      consumes:
      - application/json
      description: GetAll page
      parameters:
      - in: query
        name: email
        type: string
      - in: query
        name: password
        type: string
      - in: query
        name: user_name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: GetAll Successful
          schema:
            $ref: '#/definitions/genprotos.AllUsers'
        "401":
          description: Error while GetAll
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: GetAll User
      tags:
      - User
  /user/login:
    post:
      consumes:
      - application/json
      description: LoginUser page
      parameters:
      - description: Login
        in: body
        name: Login
        required: true
        schema:
          $ref: '#/definitions/handler.UserName'
      produces:
      - application/json
      responses:
        "200":
          description: LoginUser Successful
          schema:
            $ref: '#/definitions/token.Tokens'
        "401":
          description: Error while LoginUserd
          schema:
            type: string
      summary: /LoginUser
      tags:
      - User
  /user/register:
    post:
      consumes:
      - application/json
      description: Register page
      parameters:
      - description: Register
        in: body
        name: Register
        required: true
        schema:
          $ref: '#/definitions/genprotos.UserReq'
      produces:
      - application/json
      responses:
        "200":
          description: Register Successful
          schema:
            type: string
        "401":
          description: Error while Register
          schema:
            type: string
      summary: Register User
      tags:
      - User
  /user/update/{id}:
    put:
      consumes:
      - application/json
      description: Update page
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Update
        in: body
        name: Update
        required: true
        schema:
          $ref: '#/definitions/genprotos.UserRes'
      produces:
      - application/json
      responses:
        "200":
          description: Update Successful
          schema:
            type: string
        "401":
          description: Error while updated
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Update User
      tags:
      - User
securityDefinitions:
  BearerAuth:
    in: header
    name: Authourization
    type: apiKey
swagger: "2.0"
